name: Issue Workflow
on: 
  issues:
    type: opened
jobs:
  issue-noti-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Issue noti
        run: echo ${{ github }}